default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres       # Имя пользователя PostgreSQL
  password: oneplusz2    # Пароль, который вы указали при установке
  host: localhost          # Хост (локально)

development:
  <<: *default
  database: baqyla_invest_development

test:
  <<: *default
  database: baqyla_invest_test

production:
  <<: *default
  database: baqyla_invest_production
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>